{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-9.3.2.jar",
          "url": "gradle-9.3.2.jar",
          "size": 13156012,
          "sha512": "0fb66c55422f8904032b57e1217eed1e829d7c3a7b982f28a5528a3a22438ae66458d382c56ac51311f6a758b63342f6876734e45caae99ac9a7dde3096a1b9c",
          "sha256": "f3a1004508daeb00c4535bd56207c7ec2f958a40d7543466379e4de6bb947873",
          "sha1": "141fa146cec89cac3e59c0d484b661bf906308fc",
          "md5": "498ce9d9bb9a9a5a44149986f6aa8c0c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-settings-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "repository",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "9.3.2-15703166"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "aaptcompiler",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "crash",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "shared",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-model",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.lint",
          "module": "lint-typedef-remover",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-compiler-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.databinding",
          "module": "baseLibrary",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.utp",
          "module": "gradle-work-action-api",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.16.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.2"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "4.9"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "bundletool",
          "version": {
            "requires": "1.18.3"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-core",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.android.tools.build.jetifier",
          "module": "jetifier-processor",
          "version": {
            "requires": "1.0.0-beta10"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java-util",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.tensorflow",
          "module": "tensorflow-lite-metadata",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-gradle-plugin",
          "version": {
            "requires": "2.2.10-2.0.2"
          },
          "reason": "KSP version needs to match KGP version"
        }
      ],
      "files": [
        {
          "name": "gradle-9.3.2.jar",
          "url": "gradle-9.3.2.jar",
          "size": 13156012,
          "sha512": "0fb66c55422f8904032b57e1217eed1e829d7c3a7b982f28a5528a3a22438ae66458d382c56ac51311f6a758b63342f6876734e45caae99ac9a7dde3096a1b9c",
          "sha256": "f3a1004508daeb00c4535bd56207c7ec2f958a40d7543466379e4de6bb947873",
          "sha1": "141fa146cec89cac3e59c0d484b661bf906308fc",
          "md5": "498ce9d9bb9a9a5a44149986f6aa8c0c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.3.2-javadoc.jar",
          "url": "gradle-9.3.2-javadoc.jar",
          "size": 629635,
          "sha512": "0976aea3e5c4135b5daeb668f5c52c7a6a4bdc6dd3b57c0f32eb1c9def51a7091bdd85119c62c83ed1bce0b58101cc42e982aa0390a049b18597c8a97c2ab5da",
          "sha256": "1596056fc8e98fea531d28b99bbc9f4dc2b93cd48f22c2dba9485d50be065833",
          "sha1": "37d3caae7c4e1013c45a2775695f0d63a2f31fcb",
          "md5": "6589fc6d2c5c898b6b689bdcbe48361d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-9.3.2-sources.jar",
          "url": "gradle-9.3.2-sources.jar",
          "size": 3946786,
          "sha512": "1dc49f17e0f06138d75007a39ee4d129ff5bee74e192f3a8c87a982fcb10d32564aa7d775a3cea1e5d16057a468c14e53841ab091211363265deea6f0ed022b7",
          "sha256": "c754b8bd2ed5ba0cb6e5724153e1db57ccc99eea8559bc56b0c586e3d41cdf11",
          "sha1": "b3e46488852f6ba6a70a63cb5a021c48e2d398fc",
          "md5": "396409154e15cd475b086b15dc25e062"
        }
      ]
    }
  ]
}
