/**
 * BLUKIT UI COMPONENTS
 */
package cc.thevar.blukit.ui.screens

import androidx.compose.animation.*
import androidx.compose.animation.core.*
import androidx.compose.foundation.*
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.rounded.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.graphicsLayer
import androidx.compose.ui.layout.onGloballyPositioned
import androidx.compose.ui.layout.positionInRoot
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.zIndex
import androidx.paging.compose.LazyPagingItems
import androidx.paging.compose.itemKey
import cc.thevar.blukit.domain.model.Message
import cc.thevar.blukit.domain.model.Source
import cc.thevar.blukit.domain.model.Group
import cc.thevar.blukit.domain.model.GroupEvent
import cc.thevar.blukit.ui.navigation.Route
import cc.thevar.blukit.ui.theme.*
import cc.thevar.blukit.ui.components.*
import cc.thevar.blukit.ui.viewmodels.ConnectionUiState
import java.text.SimpleDateFormat
import java.util.Date
import kotlin.math.PI
import kotlin.math.cos
import kotlin.math.sin
import kotlin.random.Random
import kotlin.time.Duration.Companion.milliseconds

import androidx.compose.ui.res.stringResource
import cc.thevar.blukit.R

/**
 * ASSISTANT REPORT CARD: Visualizes the intelligent report generated by the Assistant.
 */
@Composable
fun AssistantReportCard(
    report: String,
    trend: String?,
    tasks: List<String> = emptyList(),
    modifier: Modifier = Modifier
) {
    Surface(
        color = StealthRose.copy(alpha = 0.05f),
        shape = RoundedCornerShape(16.dp),
        border = BorderStroke(1.dp, StealthRose.copy(alpha = 0.2f)),
        modifier = modifier.fillMaxWidth().padding(horizontal = 16.dp, vertical = 8.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically) {
                Icon(
                    imageVector = Icons.Rounded.AutoAwesome,
                    contentDescription = null,
                    tint = StealthRose,
                    modifier = Modifier.size(20.dp)
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = stringResource(R.string.assistant_report).uppercase(),
                    style = MaterialTheme.typography.labelSmall,
                    color = StealthRose,
                    fontWeight = FontWeight.Bold
                )

                if (trend != null) {
                    Spacer(modifier = Modifier.weight(1f))
                    Surface(
                        color = StealthRose,
                        shape = RoundedCornerShape(8.dp),
                    ) {
                        Box(modifier = Modifier.padding(horizontal = 8.dp, vertical = 2.dp)) {
                            Text(
                                text = trend,
                                style = MaterialTheme.typography.labelSmall,
                                color = Color.Black
                            )
                        }
                    }
                }
            }
            
            Spacer(modifier = Modifier.height(12.dp))
            
            Text(
                text = report,
                style = MaterialTheme.typography.bodyMedium,
                color = Color.White.copy(alpha = 0.9f)
            )
            
            if (tasks.isNotEmpty()) {
                Spacer(modifier = Modifier.height(12.dp))
                Text(
                    text = stringResource(R.string.assistant_tasks).uppercase(),
                    style = MaterialTheme.typography.labelSmall,
                    color = Color.White.copy(alpha = 0.4f)
                )
                tasks.forEach { task ->
                    Row(
                        modifier = Modifier.padding(top = 4.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            Icons.Rounded.TaskAlt,
                            contentDescription = null,
                            tint = StealthPrimary,
                            modifier = Modifier.size(14.dp)
                        )
                        Spacer(modifier = Modifier.width(6.6.dp))
                        Text(
                            text = task,
                            style = MaterialTheme.typography.bodySmall,
                            color = Color.White.copy(alpha = 0.7f)
                        )
                    }
                }
            }
        }
    }
}

@Composable
fun ConnectionTicker(
    state: ConnectionUiState,
    connectionList: List<Pair<Source, Message?>>,
    messageCounts: Map<String, Int>,
    localDeviceId: String,
    pulsedPeers: Set<String>,
    onMessageClick: (String) -> Unit,
    onSourceClick: (Source) -> Unit,
    onSourceLongClick: (Source) -> Unit,
    modifier: Modifier = Modifier,
    localNickname: String = "?",
    activeBubbles: List<BubbleData> = emptyList(),
    isGrouped: Boolean = true,
    reverseLayout: Boolean = true,
    themeColor: Color = StealthPrimary,
    trend: String? = null,
    onConnectionSurge: (Float) -> Unit = {}
) {
    val listState = rememberLazyListState()
    val sdf = remember { SimpleDateFormat("HH:mm", java.util.Locale.getDefault()) }
    val density = LocalDensity.current

    val isScrolling = listState.isScrollInProgress
    val hasContent = connectionList.isNotEmpty()

    val relayEvents = remember { mutableStateListOf<RelayEvent>() }
    val messageRipples = remember { mutableStateListOf<MessageRipple>() }
    val processedRelayIds = remember { mutableSetOf<String>() }
    var collectiveConnection by remember { mutableFloatStateOf(0f) }

    LaunchedEffect(activeBubbles.size) {
        if (activeBubbles.isNotEmpty()) {
            val last = activeBubbles.last()
            if (last.messageId !in processedRelayIds) {
                processedRelayIds.add(last.messageId)
                collectiveConnection = (collectiveConnection + 0.35f).coerceAtMost(1.0f)
                
                val sourceIndex = state.crowd.scannedDevices.indexOfFirst { it.id == last.senderId }
                val proximity = if (sourceIndex != -1) state.crowd.scannedDevices[sourceIndex].proximityFactor else 0.5f
                onConnectionSurge(proximity)

                val targetOffset = if (sourceIndex != -1) {
                    val source = state.crowd.scannedDevices[sourceIndex]
                    val maxRadiusPx = with(density) { 140.dp.toPx() }
                    val radiusValue = (1f - source.proximityFactor) * maxRadiusPx + with(density) { 60.dp.toPx() }
                    val angle = (sourceIndex.toDouble() / state.crowd.scannedDevices.size.coerceAtLeast(1)) * 2 * PI
                    Offset((radiusValue * cos(angle)).toFloat(), (radiusValue * sin(angle)).toFloat())
                } else Offset.Zero

                val startOffset = Offset((Random.nextFloat() - 0.5f) * 1200f, (Random.nextFloat() - 0.5f) * 1800f)
                relayEvents.add(RelayEvent(last.messageId, startOffset, targetOffset, System.currentTimeMillis()))
                
                val rippleColor = if (last.isPrivate) StealthRose else StealthPrimary
                relayEvents.add(RelayEvent(last.messageId, startOffset, targetOffset, System.currentTimeMillis(), rippleColor))
                messageRipples.add(MessageRipple(last.messageId, targetOffset, System.currentTimeMillis(), rippleColor))
            }
        }
    }

    LaunchedEffect(Unit) {
        while (true) {
            val now = System.currentTimeMillis()
            relayEvents.removeAll { now - it.startTime > 800 }
            messageRipples.removeAll { now - it.startTime > 2000 }
            collectiveConnection = (collectiveConnection - 0.04f).coerceAtLeast(0f)
            kotlinx.coroutines.delay(100.milliseconds)
        }
    }

    Box(modifier = modifier) {
        Box(
            modifier = Modifier.fillMaxSize(), 
            contentAlignment = Alignment.Center
        ) {
            VibeHeatmap(energy = collectiveConnection, themeColor = themeColor, trend = trend)
            
            PeerRadarLayer(
                devices = state.crowd.scannedDevices,
                onDeviceClick = onSourceClick,
                onDeviceLongClick = onSourceLongClick,
                selectedDevices = state.crowd.selectedDevices,
                pulsedPeers = pulsedPeers,
                bubbleSenders = remember(activeBubbles) { activeBubbles.asSequence().map { it.senderId }.toSet() },
                themeColor = themeColor,
                density = density
            )
        }

        val dimmingAlpha by animateFloatAsState(
            targetValue = if (isScrolling || hasContent) 0.95f else 0f,
            animationSpec = tween(500),
            label = "DimmingAlpha"
        )
        
        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(StealthBlack.copy(alpha = dimmingAlpha))
        )

        LazyColumn(
            state = listState,
            modifier = Modifier.fillMaxSize(),
            reverseLayout = reverseLayout,
            contentPadding = PaddingValues(top = 8.dp, bottom = 16.dp)
        ) {
            items(connectionList, key = { it.second?.messageId ?: it.first.id }) { (source, message) ->
                val id = source.persistentId ?: source.id
                val group = state.session.groups.find { it.id == (message?.groupId ?: source.id) }
                
                if (message == null && group != null) {
                    val members = if (group.id == Group.ID_GLOBAL) {
                        state.crowd.scannedDevices
                    } else {
                        state.crowd.scannedDevices.filter { it.id in group.allMemberIds || it.persistentId in group.allMemberIds }
                    }

                    val sourceCount = if (group.id == Group.ID_GLOBAL) {
                        state.crowd.scannedDevices.size
                    } else {
                        group.allMemberIds.size
                    }

                    val dynamicSubtitle = if (group.scope == Group.SCOPE_PUBLIC) "Public Group" else "Private Group"
                    val userEmoji = LocalUserEmoji.current

                    GroupSummary(
                        title = group.name,
                        subtitle = dynamicSubtitle,
                        icon = if (group.scope == Group.SCOPE_PUBLIC) Icons.Rounded.Public else Icons.Rounded.Hearing,
                        themeColor = if (group.scope == Group.SCOPE_PUBLIC) StealthPrimary else StealthRose,
                        count = sourceCount,
                        lastUpdate = sdf.format(Date(group.lastMessageTimestamp)),
                        onClick = { onMessageClick(group.id) },
                        aiTrend = source.statusLabel,
                        leftContent = if (group.id == Group.ID_GLOBAL) {
                            {
                                PersonaSignature(
                                    source = Source(id = "YOU", name = localNickname, emoji = userEmoji),
                                    isPulsed = false,
                                    isSelected = false,
                                    size = 44.dp,
                                    themeColor = StealthPrimary,
                                    isMe = true,
                                    onClick = { onSourceClick(Source(id = "YOU", name = localNickname, emoji = userEmoji)) }
                                )
                            }
                        } else null,
                        topContent = {
                            GroupMiniRadar(
                                group = group,
                                members = members,
                                isDefaultGroup = group.id == Group.ID_GLOBAL,
                                themeColor = if (group.scope == Group.SCOPE_PUBLIC) StealthPrimary else StealthRose,
                                onSourceClick = onSourceClick,
                                onSourceLongClick = onSourceLongClick,
                                activeBubbles = activeBubbles
                            )
                        },
                        modifier = Modifier.padding(horizontal = 8.dp)
                    )
                } else {
                    val count = if (isGrouped) messageCounts[id] ?: 0 else 0
                    
                    MessageItem(
                        message = message,
                        isSelected = source.id in state.crowd.selectedDevices,
                        senderSource = source,
                        replyCount = count,
                        isPulsed = id in pulsedPeers,
                        isMe = message?.senderId == localDeviceId || source.id == localDeviceId,
                        isGrouped = isGrouped,
                        isMutual = source.id in state.session.connectedTies,
                        rowId = id,
                        onMessageClick = { message?.messageId?.let { onMessageClick(it) } ?: onSourceLongClick(source) },
                        onSourceLongClick = { onSourceLongClick(source) },
                        topContent = {
                            if (isGrouped && group != null) {
                                val members = state.crowd.scannedDevices.filter { it.id in group.allMemberIds || it.persistentId in group.allMemberIds }
                                GroupMiniRadar(
                                    group = group,
                                    members = members,
                                    themeColor = if (group.scope == Group.SCOPE_PUBLIC) StealthPrimary else StealthRose,
                                    onSourceClick = onSourceClick,
                                    onSourceLongClick = onSourceLongClick,
                                    activeBubbles = activeBubbles,
                                    modifier = Modifier.height(60.dp).padding(vertical = 4.dp)
                                )
                            }
                        }
                    )
                }
            }
        }
    }
}

@Composable
fun PagedConnectionTicker(
    state: ConnectionUiState,
    pagedMessages: LazyPagingItems<Message>,
    messageCounts: Map<String, Int>,
    localDeviceId: String,
    pulsedPeers: Set<String>,
    onMessageClick: (String) -> Unit,
    onSourceClick: (Source) -> Unit,
    onSourceLongClick: (Source) -> Unit,
    modifier: Modifier = Modifier,
    localNickname: String = "?",
    activeBubbles: List<BubbleData> = emptyList(),
    isGrouped: Boolean = true,
    reverseLayout: Boolean = true,
    themeColor: Color = StealthPrimary,
    trend: String? = null,
    onConnectionSurge: (Float) -> Unit = {}
) {
    val listState = rememberLazyListState()
    val density = LocalDensity.current

    val isScrolling = listState.isScrollInProgress
    val hasContent = pagedMessages.itemCount > 0

    val relayEvents = remember { mutableStateListOf<RelayEvent>() }
    val messageRipples = remember { mutableStateListOf<MessageRipple>() }
    var collectiveConnection by remember { mutableFloatStateOf(0f) }

    Box(modifier = modifier) {
        Box(
            modifier = Modifier.fillMaxSize(), 
            contentAlignment = Alignment.Center
        ) {
            VibeHeatmap(energy = collectiveConnection, themeColor = themeColor, trend = trend)
            
            PeerRadarLayer(
                devices = state.crowd.scannedDevices,
                onDeviceClick = onSourceClick,
                onDeviceLongClick = onSourceLongClick,
                selectedDevices = state.crowd.selectedDevices,
                pulsedPeers = pulsedPeers,
                bubbleSenders = remember(activeBubbles) { activeBubbles.asSequence().map { it.senderId }.toSet() },
                themeColor = themeColor,
                density = density
            )
        }

        val dimmingAlpha by animateFloatAsState(
            targetValue = if (isScrolling || hasContent) 0.95f else 0f,
            animationSpec = tween(500),
            label = "DimmingAlpha"
        )
        
        Box(
            modifier = Modifier
                .fillMaxSize()
                .background(StealthBlack.copy(alpha = dimmingAlpha))
        )

        LazyColumn(
            state = listState,
            modifier = Modifier.fillMaxSize(),
            reverseLayout = reverseLayout,
            contentPadding = PaddingValues(top = 8.dp, bottom = 16.dp)
        ) {
            items(
                count = pagedMessages.itemCount,
                key = pagedMessages.itemKey { it.messageId }
            ) { index ->
                val message = pagedMessages[index]
                if (message != null) {
                    val source = state.crowd.scannedDevices.find { it.id == message.senderId || it.persistentId == message.senderId } 
                        ?: Source(id = message.senderId, name = message.senderName, emoji = message.senderEmoji ?: "👤")
                    
                    val id = source.persistentId ?: source.id
                    val group = state.session.groups.find { it.id == message.groupId }
                    
                    val count = if (isGrouped) messageCounts[id] ?: 0 else 0
                    
                    MessageItem(
                        message = message,
                        isSelected = source.id in state.crowd.selectedDevices,
                        senderSource = source,
                        replyCount = count,
                        isPulsed = id in pulsedPeers,
                        isMe = message.senderId == localDeviceId || source.id == localDeviceId,
                        isGrouped = isGrouped,
                        isMutual = source.id in state.session.connectedTies,
                        rowId = id,
                        onMessageClick = { onMessageClick(message.messageId) },
                        onSourceLongClick = { onSourceLongClick(source) },
                        topContent = {
                            if (isGrouped && group != null) {
                                val members = state.crowd.scannedDevices.filter { it.id in group.allMemberIds || it.persistentId in group.allMemberIds }
                                GroupMiniRadar(
                                    group = group,
                                    members = members,
                                    themeColor = if (group.scope == Group.SCOPE_PUBLIC) StealthPrimary else StealthRose,
                                    onSourceClick = onSourceClick,
                                    onSourceLongClick = onSourceLongClick,
                                    activeBubbles = activeBubbles,
                                    modifier = Modifier.height(60.dp).padding(vertical = 4.dp)
                                )
                            }
                        }
                    )
                }
            }
        }
    }
}

@Composable
fun MessageItem(
    message: Message?,
    isSelected: Boolean,
    senderSource: Source?,
    replyCount: Int,
    isPulsed: Boolean,
    isMe: Boolean,
    isGrouped: Boolean,
    isMutual: Boolean,
    rowId: String,
    onMessageClick: () -> Unit,
    onSourceLongClick: () -> Unit,
    topContent: @Composable (() -> Unit)? = null
) {
    val timestamp = message?.let { SimpleDateFormat("HH:mm", java.util.Locale.getDefault()).format(Date(it.timestamp)) } ?: ""
    val bubbleColor = if (isMe) StealthPrimary.copy(alpha = 0.15f) else StealthSurface
    val alignment = if (isMe) Alignment.End else Alignment.Start

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 12.dp, vertical = 4.dp),
        horizontalAlignment = alignment
    ) {
        if (!isMe && !isGrouped && message != null) {
            Text(
                text = message.senderName,
                style = MaterialTheme.typography.labelSmall,
                color = Color.White.copy(alpha = 0.5f),
                modifier = Modifier.padding(start = 12.dp, bottom = 2.dp)
            )
        }

        Surface(
            color = bubbleColor,
            shape = RoundedCornerShape(
                topStart = 16.dp,
                topEnd = 16.dp,
                bottomStart = if (isMe) 16.dp else 4.dp,
                bottomEnd = if (isMe) 4.dp else 16.dp
            ),
            border = BorderStroke(1.dp, Color.White.copy(alpha = 0.05f)),
            onClick = onMessageClick,
            modifier = Modifier
                .widthIn(max = 300.dp)
                .combinedClickable(
                    onClick = onMessageClick,
                    onLongClick = onSourceLongClick
                )
        ) {
            Column(modifier = Modifier.padding(12.dp)) {
                MessageContent(message = message, themeColor = if (isMe) StealthPrimary else StealthRose)
                
                Row(
                    modifier = Modifier.align(Alignment.End).padding(top = 4.dp),
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text(
                        text = timestamp,
                        style = MaterialTheme.typography.labelSmall.copy(fontSize = 10.sp),
                        color = Color.White.copy(alpha = 0.3f)
                    )
                    if (isMe && message?.status == Message.STATUS_DELIVERED) {
                        Spacer(modifier = Modifier.width(4.dp))
                        Icon(Icons.Rounded.DoneAll, contentDescription = null, tint = StealthPrimary, modifier = Modifier.size(12.dp))
                    }
                }
            }
        }
    }
}

@Composable
fun SunkRecordVault(
    archivedGroups: List<Group>,
    onRestore: (String) -> Unit,
    onDismiss: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = StealthBlack,
        shape = RoundedCornerShape(28.dp),
        title = { 
            Text(
                text = "Group Archive", 
                style = MaterialTheme.typography.titleMedium,
                color = StealthPrimary
            ) 
        },
        text = {
            LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                items(archivedGroups) { group ->
                    GroupSummary(
                        title = group.name,
                        subtitle = "Archived",
                        icon = Icons.Rounded.Unarchive,
                        themeColor = StealthGray,
                        count = -1,
                        lastUpdate = "SUNK",
                        onClick = { onRestore(group.id) }
                    )
                }
            }
        },
        confirmButton = { 
            TextButton(onClick = onDismiss) { 
                Text(
                    text = "CLOSE", 
                    style = MaterialTheme.typography.labelLarge,
                    color = StealthPrimary
                ) 
            } 
        }
    )
}

@Composable
fun BlukitTip(
    text: String,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier,
    themeColor: Color = StealthAmber
) {
    Surface(
        modifier = modifier
            .padding(horizontal = 16.dp, vertical = 12.dp)
            .fillMaxWidth()
            .graphicsLayer { alpha = 0.98f },
        color = StealthSurface,
        shape = RoundedCornerShape(20.dp),
        border = BorderStroke(1.dp, themeColor.copy(alpha = 0.2f))
    ) {
        Row(
            modifier = Modifier.padding(16.dp), 
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(40.dp)
                    .background(themeColor.copy(alpha = StealthAlphaLow), CircleShape),
                contentAlignment = Alignment.Center
            ) {
                Icon(
                    imageVector = Icons.Rounded.TipsAndUpdates, 
                    contentDescription = null, 
                    tint = themeColor, 
                    modifier = Modifier.size(20.dp)
                )
            }
            Spacer(modifier = Modifier.width(16.dp))
            Text(
                text = text, 
                style = MaterialTheme.typography.bodySmall,
                color = Color.White.copy(alpha = 0.9f),
                modifier = Modifier.weight(1f)
            )
            IconButton(onClick = onDismiss, modifier = Modifier.size(32.dp)) {
                Icon(
                    imageVector = Icons.Rounded.Close, 
                    contentDescription = "Dismiss", 
                    tint = Color.White.copy(alpha = 0.3f), 
                    modifier = Modifier.size(16.dp)
                )
            }
        }
    }
}

@Composable
fun IdentityInput(
    onSave: (String, String) -> Unit
) {
    var name by remember { mutableStateOf("") }
    var emoji by remember { mutableStateOf("👤") }
    
    Column(
        horizontalAlignment = Alignment.CenterHorizontally,
        modifier = Modifier.fillMaxWidth().padding(24.dp)
    ) {
        Text(text = stringResource(R.string.identity_title).uppercase(), style = MaterialTheme.typography.labelSmall, color = StealthAmber)
        Spacer(modifier = Modifier.height(16.dp))
        IdentitySetup(
            nickname = name,
            emoji = emoji,
            onNicknameChange = { name = it },
            onEmojiChange = { emoji = it },
            onDone = { onSave(name, emoji) },
            onDismiss = { /* No-op */ }
        )
    }
}

@Composable
fun rememberSpreadPermissionsState(
    allPermissions: List<String>,
    essentialPermissions: List<String>
): SpreadPermissionsState {
    val context = androidx.compose.ui.platform.LocalContext.current
    var allGranted by remember { mutableStateOf(false) }
    var essentialGranted by remember { mutableStateOf(false) }
    
    val launcher = androidx.activity.compose.rememberLauncherForActivityResult(
        contract = androidx.activity.result.contract.ActivityResultContracts.RequestMultiplePermissions()
    ) { result ->
        allGranted = result.values.all { it }
        essentialGranted = essentialPermissions.all { result[it] == true }
    }

    LaunchedEffect(Unit) {
        allGranted = allPermissions.all { 
            androidx.core.content.ContextCompat.checkSelfPermission(context, it) == android.content.pm.PackageManager.PERMISSION_GRANTED 
        }
        essentialGranted = essentialPermissions.all {
            androidx.core.content.ContextCompat.checkSelfPermission(context, it) == android.content.pm.PackageManager.PERMISSION_GRANTED
        }
    }

    return remember(allGranted, essentialGranted) {
        object : SpreadPermissionsState {
            override val allPermissionsGranted = allGranted
            override val essentialPermissionsGranted = essentialGranted
            override val shouldShowRationale = true // Simplified
            override fun launchMultiplePermissionRequest() {
                launcher.launch(allPermissions.toTypedArray())
            }
        }
    }
}

@Composable
fun TickerSectionHeader(title: String, color: Color) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(horizontal = 16.dp, vertical = 8.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Text(
            text = title, 
            style = MaterialTheme.typography.labelSmall,
            color = color.copy(alpha = StealthAlphaHigh),
            letterSpacing = 1.sp
        )
        Spacer(modifier = Modifier.width(12.dp))
        HorizontalDivider(color = color.copy(alpha = 0.1f), modifier = Modifier.weight(1f))
    }
}

@Composable
fun GroupSummary(
    title: String,
    subtitle: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    themeColor: Color,
    count: Int,
    lastUpdate: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    aiTrend: String? = null,
    leftContent: @Composable (() -> Unit)? = null,
    topContent: @Composable (() -> Unit)? = null
) {
    Surface(
        onClick = onClick,
        color = StealthSurface,
        shape = RoundedCornerShape(20.dp),
        border = BorderStroke(1.dp, Color.White.copy(alpha = 0.05f)),
        modifier = modifier
    ) {
        Column {
            if (topContent != null) {
                topContent()
            }
            Row(
                modifier = Modifier.padding(16.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                if (leftContent != null) {
                    leftContent()
                    Spacer(modifier = Modifier.width(16.dp))
                } else {
                    Surface(
                        color = themeColor.copy(alpha = StealthAlphaLow),
                        shape = CircleShape,
                        modifier = Modifier.size(48.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center) {
                            Icon(icon, contentDescription = null, tint = themeColor, modifier = Modifier.size(24.dp))
                        }
                    }
                    Spacer(modifier = Modifier.width(16.dp))
                }
                
                Column(modifier = Modifier.weight(1f)) {
                    Text(text = title, style = MaterialTheme.typography.titleMedium, color = Color.White)
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(text = subtitle, style = MaterialTheme.typography.labelSmall, color = Color.White.copy(alpha = 0.4f))
                        if (aiTrend != null) {
                            Spacer(modifier = Modifier.width(8.dp))
                            Icon(Icons.Rounded.AutoAwesome, contentDescription = null, tint = StealthAmber, modifier = Modifier.size(12.dp))
                            Spacer(modifier = Modifier.width(4.dp))
                            Text(text = aiTrend, style = MaterialTheme.typography.labelSmall, color = StealthAmber)
                        }
                    }
                }
                
                if (count >= 0) {
                    Column(horizontalAlignment = Alignment.End) {
                        Text(text = count.toString(), style = MaterialTheme.typography.titleMedium, color = themeColor)
                        Text(text = lastUpdate, style = MaterialTheme.typography.labelSmall, color = Color.White.copy(alpha = 0.3f))
                    }
                }
            }
        }
    }
}

@Composable
fun MessageContent(message: Message?, themeColor: Color) {
    if (message == null) return
    
    when (message.type) {
        Message.TYPE_TEXT -> {
            Text(
                text = message.content,
                style = MaterialTheme.typography.bodyLarge,
                color = Color.White.copy(alpha = 0.9f)
            )
        }
        Message.TYPE_IMAGE -> {
            Surface(
                modifier = Modifier
                    .fillMaxWidth()
                    .height(200.dp)
                    .clip(RoundedCornerShape(12.dp)),
                color = StealthSurface
            ) {
                Box(contentAlignment = Alignment.Center) {
                    Icon(Icons.Rounded.Image, contentDescription = null, tint = Color.White.copy(alpha = 0.1f), modifier = Modifier.size(48.dp))
                }
            }
        }
        Message.TYPE_FILE -> {
            Surface(
                color = Color.White.copy(alpha = 0.05f),
                shape = RoundedCornerShape(12.dp),
                border = BorderStroke(1.dp, Color.White.copy(alpha = 0.1f))
            ) {
                Row(modifier = Modifier.padding(12.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Rounded.Description, contentDescription = null, tint = themeColor, modifier = Modifier.size(24.dp))
                    Spacer(modifier = Modifier.width(12.dp))
                    Column {
                        Text(text = message.fileName ?: "Document", style = MaterialTheme.typography.bodySmall, color = Color.White)
                        Text(text = "${(message.fileSize ?: 0) / 1024} KB", style = MaterialTheme.typography.labelSmall, color = Color.White.copy(alpha = 0.4f))
                    }
                }
            }
        }
        Message.TYPE_NOTE_UPDATE, Message.TYPE_ASSIGNMENT_TASK -> {
             cc.thevar.blukit.ui.components.MessageRecordItem(
                record = message,
                onStatusChange = { }, 
                themeColor = themeColor
            )
        }
        Message.TYPE_AI_SUMMARY -> {
            Surface(
                color = StealthAmber.copy(alpha = 0.1f),
                shape = RoundedCornerShape(8.dp),
                border = BorderStroke(1.dp, StealthAmber.copy(alpha = 0.2f))
            ) {
                Row(modifier = Modifier.padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
                    Icon(Icons.Rounded.AutoAwesome, contentDescription = null, tint = StealthAmber, modifier = Modifier.size(14.dp))
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(text = message.content, style = MaterialTheme.typography.bodySmall, color = StealthAmber)
                }
            }
        }
    }
}

@Composable
fun SyncProgressIndicator(progress: Float?) {
    if (progress != null) {
        LinearProgressIndicator(
            progress = { progress },
            modifier = Modifier.fillMaxWidth().height(2.dp),
            color = StealthPrimary,
            trackColor = Color.Transparent
        )
    }
}

@Composable
fun PermissionRequiredField(
    isPermanentlyDenied: Boolean,
    onGrantClick: () -> Unit
) {
    Column(
        modifier = Modifier.fillMaxSize().padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(Icons.Rounded.Security, contentDescription = null, tint = StealthError, modifier = Modifier.size(64.dp))
        Spacer(modifier = Modifier.height(24.dp))
        Text(
            text = stringResource(R.string.permissions_required).uppercase(),
            style = MaterialTheme.typography.titleLarge,
            color = Color.White
        )
        Spacer(modifier = Modifier.height(16.dp))
        Text(
            text = if (isPermanentlyDenied) "Nearby connection requires location and bluetooth permissions. Please enable them in settings." else "Grant permissions to sense and connect with nearby people.",
            style = MaterialTheme.typography.bodyMedium,
            color = Color.White.copy(alpha = 0.6f),
            textAlign = TextAlign.Center
        )
        Spacer(modifier = Modifier.height(32.dp))
        Button(
            onClick = onGrantClick,
            colors = ButtonDefaults.buttonColors(containerColor = StealthPrimary, contentColor = Color.Black),
            shape = RoundedCornerShape(12.dp)
        ) {
            Text(text = if (isPermanentlyDenied) "OPEN SETTINGS" else "GRANT ACCESS")
        }
    }
}

@Composable
fun SourceOptionsMenu(
    device: Source,
    isTied: Boolean,
    isBlocked: Boolean,
    isRequesting: Boolean,
    activeGroupId: String?,
    isAlreadyInActiveGroup: Boolean,
    onMessage: () -> Unit,
    onAccept: () -> Unit,
    onDeny: () -> Unit,
    onDisconnect: () -> Unit,
    onSelect: () -> Unit,
    onIdentify: () -> Unit,
    onBlock: () -> Unit,
    onUnblock: () -> Unit,
    onSync: () -> Unit,
    onAddToGroup: (String) -> Unit,
    onRemoveFromGroup: (String) -> Unit,
    onDismiss: () -> Unit
) {
    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = StealthSurface,
        title = { 
            Row(verticalAlignment = Alignment.CenterVertically) {
                Text(text = device.emoji, fontSize = 24.sp)
                Spacer(modifier = Modifier.width(12.dp))
                Text(text = (device.name ?: "UNKNOWN").uppercase(), style = MaterialTheme.typography.titleMedium, color = Color.White)
            }
        },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                if (isRequesting) {
                    MenuActionItem(Icons.Rounded.Check, "Accept Request", StealthPrimary, onClick = onAccept)
                    MenuActionItem(Icons.Rounded.Close, "Deny Request", StealthError, onClick = onDeny)
                }
                
                MenuActionItem(Icons.Rounded.Message, "Private Whisper", StealthRose, onClick = onMessage)
                MenuActionItem(Icons.Rounded.Fingerprint, "Identify Source", StealthAmber, onClick = onIdentify)
                
                if (activeGroupId != null && activeGroupId != Group.ID_GLOBAL) {
                    if (isAlreadyInActiveGroup) {
                        MenuActionItem(Icons.Rounded.PersonRemove, "Remove from Group", StealthError, onClick = { onRemoveFromGroup(activeGroupId) })
                    } else {
                        MenuActionItem(Icons.Rounded.PersonAdd, "Add to Group", StealthPrimary, onClick = { onAddToGroup(activeGroupId) })
                    }
                }
                
                MenuActionItem(Icons.Rounded.Sync, "Force Sync History", StealthPrimary, onClick = onSync)
                
                if (isBlocked) {
                    MenuActionItem(Icons.Rounded.LockOpen, "Unblock Source", StealthPrimary, onClick = onUnblock)
                } else {
                    MenuActionItem(Icons.Rounded.Block, "Block Source", StealthError, onClick = onBlock)
                }
            }
        },
        confirmButton = {
            TextButton(onClick = onDismiss) { Text("CLOSE", color = Color.White.copy(alpha = 0.4f)) }
        }
    )
}

interface SpreadPermissionsState {
    val allPermissionsGranted: Boolean
    val essentialPermissionsGranted: Boolean
    val shouldShowRationale: Boolean
    fun launchMultiplePermissionRequest()
}
