{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.utp",
    "module": "gradle-work-action-api",
    "version": "32.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-work-action-api-32.3.2.jar",
          "url": "gradle-work-action-api-32.3.2.jar",
          "size": 32073,
          "sha512": "4fbd0f42609bd8680c7398c5380add5161111c23b2f4ceac587309ed41da7783a632548dd88a37ef4763d122e92692822c81039761aff4e5f11ac77a20f7d858",
          "sha256": "de87773a677e87f619c751c306af6ee73a04a7b26e5f205fff287728d8af4ace",
          "sha1": "9f8423f22abe1068b0a8d5f144b49ac7fb148c83",
          "md5": "0199f7b1ec2ae7ccc80fa065654cd1ff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-work-action-api-32.3.2.jar",
          "url": "gradle-work-action-api-32.3.2.jar",
          "size": 32073,
          "sha512": "4fbd0f42609bd8680c7398c5380add5161111c23b2f4ceac587309ed41da7783a632548dd88a37ef4763d122e92692822c81039761aff4e5f11ac77a20f7d858",
          "sha256": "de87773a677e87f619c751c306af6ee73a04a7b26e5f205fff287728d8af4ace",
          "sha1": "9f8423f22abe1068b0a8d5f144b49ac7fb148c83",
          "md5": "0199f7b1ec2ae7ccc80fa065654cd1ff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-work-action-api-32.3.2-javadoc.jar",
          "url": "gradle-work-action-api-32.3.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-work-action-api-32.3.2-sources.jar",
          "url": "gradle-work-action-api-32.3.2-sources.jar",
          "size": 9617,
          "sha512": "e84d62defdf0e5f0c2f6b9e1af3ebb53305036295244cdfa67df7a76bbaf42e0975be7d81c0254d7324e9a92be7570f7dcdccb9c2e12518b3a22ae90460e3765",
          "sha256": "d7281a4fee6c4308568590f9ca5c4d797a79d45e297939af00f4e84ca6aceddc",
          "sha1": "331faf16b48c04c85b543934c7f3db45fe1ef7ca",
          "md5": "eda73f1869f752880931f8102f502e3f"
        }
      ]
    }
  ]
}
