{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.moshi",
    "module": "moshi-adapters",
    "version": "1.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-adapters-1.15.2.jar",
          "url": "moshi-adapters-1.15.2.jar",
          "size": 14247,
          "sha512": "1ef6b4148526786760bf88747cd639a0164b4bf9e9d1da6b6dd1691b953c92180bfbaa8a665532fea278c167d18f089cdf8f95365155a4415d7f62c962521ea9",
          "sha256": "efa90fb3419a5a88bd5e029cbafdcecce1812430b15cb86770f60eaf0b45c409",
          "sha1": "edeca8b0df58cf1ad4d1d1136f9dfd536b243b3b",
          "md5": "768f6ad4e998d60185da31d7d43c9800"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-adapters-1.15.2.jar",
          "url": "moshi-adapters-1.15.2.jar",
          "size": 14247,
          "sha512": "1ef6b4148526786760bf88747cd639a0164b4bf9e9d1da6b6dd1691b953c92180bfbaa8a665532fea278c167d18f089cdf8f95365155a4415d7f62c962521ea9",
          "sha256": "efa90fb3419a5a88bd5e029cbafdcecce1812430b15cb86770f60eaf0b45c409",
          "sha1": "edeca8b0df58cf1ad4d1d1136f9dfd536b243b3b",
          "md5": "768f6ad4e998d60185da31d7d43c9800"
        }
      ]
    }
  ]
}
