{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.ben-manes.caffeine",
    "module": "caffeine",
    "version": "3.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.49.0"
          }
        }
      ],
      "files": [
        {
          "name": "caffeine-3.2.4.jar",
          "url": "caffeine-3.2.4.jar",
          "size": 1029147,
          "sha512": "6923d1b826e3723a9d58b092626045bdbac48dd91e758b3b78164de31105035343145d14c20a00b62658b7d1dff2a5cfb7475b200cc630dcd967c4732c2628ee",
          "sha256": "9d9d2cfd681fd9272ded3d27c9930db12f89f732345975aa113ebc223bbf1224",
          "sha1": "c63b303adf59c733d2a96125ad6670e938a2c15d",
          "md5": "04d655feb58be297a86fa2814a1f1ef8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.errorprone",
          "module": "error_prone_annotations",
          "version": {
            "requires": "2.49.0"
          }
        }
      ],
      "files": [
        {
          "name": "caffeine-3.2.4.jar",
          "url": "caffeine-3.2.4.jar",
          "size": 1029147,
          "sha512": "6923d1b826e3723a9d58b092626045bdbac48dd91e758b3b78164de31105035343145d14c20a00b62658b7d1dff2a5cfb7475b200cc630dcd967c4732c2628ee",
          "sha256": "9d9d2cfd681fd9272ded3d27c9930db12f89f732345975aa113ebc223bbf1224",
          "sha1": "c63b303adf59c733d2a96125ad6670e938a2c15d",
          "md5": "04d655feb58be297a86fa2814a1f1ef8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caffeine-3.2.4-javadoc.jar",
          "url": "caffeine-3.2.4-javadoc.jar",
          "size": 4340303,
          "sha512": "613c32cff977fdc085058876df79700e0a472d764c369a44c9d78df5f8461500477fc63a95fcbec14d7bd061f4a97fa7eb546937266b4bbc4b405dba89e86f4f",
          "sha256": "b12285ddffd942b7d01f0aed4c7612cd2edebce73cc087f08d85f5784fbd1a38",
          "sha1": "a584e1982fa014b18906de7c39df24261ba37b77",
          "md5": "64815c027d8d2beb0ef879a8c6699004"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "caffeine-3.2.4-sources.jar",
          "url": "caffeine-3.2.4-sources.jar",
          "size": 812624,
          "sha512": "55ca3aa543907594806477cb9d04735dccca8e574f0403938bb94709310b57bdceb61d93860cf99308ab0ca4e84fc2e3c4fdb32e91122f4fe78494bbe3850adf",
          "sha256": "5079e1b327d79e2fc8ae3f5927587e59c968603e63785fb33479acd8b732211d",
          "sha1": "8fe2333048b29e8fabaf00692840fdcef67d3561",
          "md5": "217331e7066ca2e1d7618d4d0cef3268"
        }
      ]
    }
  ]
}
