{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zacsweers.moshix",
    "module": "moshi-sealed-runtime",
    "version": "0.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-sealed-runtime-0.30.0.jar",
          "url": "moshi-sealed-runtime-0.30.0.jar",
          "size": 11165,
          "sha512": "ac6fdadac8089553cc1c83c40c56216b9111bf8188b27fe8d549a23317e71fd498a6d8d0fd9831ee4166b0374a1ed4bd918d4acb775cd5903d8a181b9db0163a",
          "sha256": "f048d2c1ffa376dd7ce55455a9ac675d19294e8e8e4f023d567e10ef9bb28933",
          "sha1": "dc7bd27c1a107f32742c1b7262cfabdb10d42b45",
          "md5": "d3a4275f6f833242b48729d99deacc45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-sealed-runtime-0.30.0.jar",
          "url": "moshi-sealed-runtime-0.30.0.jar",
          "size": 11165,
          "sha512": "ac6fdadac8089553cc1c83c40c56216b9111bf8188b27fe8d549a23317e71fd498a6d8d0fd9831ee4166b0374a1ed4bd918d4acb775cd5903d8a181b9db0163a",
          "sha256": "f048d2c1ffa376dd7ce55455a9ac675d19294e8e8e4f023d567e10ef9bb28933",
          "sha1": "dc7bd27c1a107f32742c1b7262cfabdb10d42b45",
          "md5": "d3a4275f6f833242b48729d99deacc45"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moshi-sealed-runtime-0.30.0-sources.jar",
          "url": "moshi-sealed-runtime-0.30.0-sources.jar",
          "size": 7849,
          "sha512": "33ce1b18e79c82a03addd2723e31f8342ccda221256c45f51468472357f5db08e6f58bdbbc4f6d91fb410402d119979c39624e44e3446d887ab9e0d3f5b88e8f",
          "sha256": "1ec5041560f38124b2394f690ed8037a22c8e76d13fd3a0b4f7cc5e6530dfbfa",
          "sha1": "0d6a6b456b9fbe4d79825d1daf2d134d651a6ac0",
          "md5": "cb59601bfcc99cf2edcbdb30a95fb4ea"
        }
      ]
    }
  ]
}
