{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "aaptcompiler",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aaptcompiler-9.3.2.jar",
          "url": "aaptcompiler-9.3.2.jar",
          "size": 493886,
          "sha512": "38981f87e2d432bcd6890a262cb817994a638cde066e50a03cf375074db9d2dece76409b0bbf37f1c78882da4cea9d935b540401113130540bd9da72c3716329",
          "sha256": "aaa3da8e958ac94c3352284224c82c0f153dcbc9376d9ddc0d8e935087849302",
          "sha1": "09cdb9896f5ca8b245bc9cac168250c5d88779c5",
          "md5": "6931e599e9f64d48baa8e3eb1fe6c64c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "aapt2-proto",
          "version": {
            "requires": "9.3.2-15703166"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.25.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "aaptcompiler-9.3.2.jar",
          "url": "aaptcompiler-9.3.2.jar",
          "size": 493886,
          "sha512": "38981f87e2d432bcd6890a262cb817994a638cde066e50a03cf375074db9d2dece76409b0bbf37f1c78882da4cea9d935b540401113130540bd9da72c3716329",
          "sha256": "aaa3da8e958ac94c3352284224c82c0f153dcbc9376d9ddc0d8e935087849302",
          "sha1": "09cdb9896f5ca8b245bc9cac168250c5d88779c5",
          "md5": "6931e599e9f64d48baa8e3eb1fe6c64c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-9.3.2-javadoc.jar",
          "url": "aaptcompiler-9.3.2-javadoc.jar",
          "size": 81065,
          "sha512": "50b2a55c05905cfce9f4d49cab238bd811f2c976ceabb8c5c9980d3a4445a9da09fea2c1ca3b726ea163f612412eceef07aaa7de45881269ce6417ecce715f46",
          "sha256": "9c7e586cbe406a4e730c012ea10d5b139baee3c2d86186b909e832e9268d0aa7",
          "sha1": "3736bd20a12416d959b4ab7b3cef6ef31f29d684",
          "md5": "eded224dd6079aac42bf31fdcf1a2363"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "aaptcompiler-9.3.2-sources.jar",
          "url": "aaptcompiler-9.3.2-sources.jar",
          "size": 152179,
          "sha512": "a2ae0ad4bc6f4d23679ea08b0c5a8fd825bf1a781a9221f995bf363422c1d83d52e8c9b8a036dd9bc253271c4e474c516c982bbe817d51e9ffc4b8c8afc78d81",
          "sha256": "60237e90334d6db447c37a825e35f7ff83337c1542ea0e9f0aee06b6e0484336",
          "sha1": "5fc1181f1cb14ecbe416aae29b74a1bbe33c232c",
          "md5": "e899cd9ba827d7c9f42c76e904de6d5b"
        }
      ]
    }
  ]
}
