{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.zacsweers.moshix",
    "module": "moshi-sealed-reflect",
    "version": "0.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-sealed-reflect-0.30.0.jar",
          "url": "moshi-sealed-reflect-0.30.0.jar",
          "size": 10567,
          "sha512": "804d063102332a9322acf27ce3fc30f40281066b62be71b2eb66736fae422b72f0ac66f78adb8baaf06d98e975f94f067c1d10b6657ee5d491f8db9ee1784108",
          "sha256": "bcfdaa32499c6288ea8b6d358b66649c05da89ff661c4363d43d33d67e60a7b9",
          "sha1": "879478ca34249cf3fa9f21c6f8eac738b6f5836e",
          "md5": "ac3675642b78686cca7a02e613bd0675"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.zacsweers.moshix",
          "module": "moshi-sealed-runtime",
          "version": {
            "requires": "0.30.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.15.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "moshi-sealed-reflect-0.30.0.jar",
          "url": "moshi-sealed-reflect-0.30.0.jar",
          "size": 10567,
          "sha512": "804d063102332a9322acf27ce3fc30f40281066b62be71b2eb66736fae422b72f0ac66f78adb8baaf06d98e975f94f067c1d10b6657ee5d491f8db9ee1784108",
          "sha256": "bcfdaa32499c6288ea8b6d358b66649c05da89ff661c4363d43d33d67e60a7b9",
          "sha1": "879478ca34249cf3fa9f21c6f8eac738b6f5836e",
          "md5": "ac3675642b78686cca7a02e613bd0675"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "moshi-sealed-reflect-0.30.0-sources.jar",
          "url": "moshi-sealed-reflect-0.30.0-sources.jar",
          "size": 4073,
          "sha512": "65728606e3e34d92c730d7e8e9faeb37b04c683db1508b8b5ea2449974ff6c0f06383af83ff208ce45d1e4e169b79b032a5fbd34c722ddb68588d7fd1f1a60e7",
          "sha256": "85adf1c0b6a742c16437d6362d0bd482210f2e72c8476339b0d63549ec2c417d",
          "sha1": "5e00a342b867756a28913aed2087b6580ca8a46b",
          "md5": "da8efb8cbb844a3fb33cc113fa8e9c6b"
        }
      ]
    }
  ]
}
