package cc.thevar.blukit.domain.model.intelligence

import kotlinx.serialization.Serializable

/**
 * A synthesized insight of a mesh room generated by local AI.
 */
@Serializable
data class MeshInsight(
    val groupId: String,
    val summary: String,
    val topKeywords: List<String>,
    val sentimentScore: Float, // -1.0 to 1.0
    val derivedTimestamp: Long,
    val messageCountSampled: Int
)
