/**
 * BLUKIT CORE DOMAIN: CROWD AI
 *
 * Models for decentralized intelligence and swarm logic.
 */
package cc.thevar.blukit.domain.model.intelligence

import kotlinx.serialization.Serializable

/**
 * A synthesized summary of a crowd context generated by local AI.
 */
@Serializable
data class ResonanceSummary(
    val groupId: String,
    val summary: String,
    val topKeywords: List<String>,
    val sentimentScore: Float, // -1.0 to 1.0
    val derivedTimestamp: Long,
    val pulseCountSampled: Int
)
