{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autonomousapps",
    "module": "variant-artifacts",
    "version": "0.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "variant-artifacts-0.7.0.jar",
          "url": "variant-artifacts-0.7.0.jar",
          "size": 29063,
          "sha512": "4b9f62cfccf074534a2a959b633a7c5b7bd785340c4c570a29f35e76de9fe53e3de4919f1818a1d2a558568e1dc3363ee250b9c6aeffcb67d1a6b873b9148f7b",
          "sha256": "da74ae4a28b302eb27fc8f38990aef916b2b24c0127df926295810c710f87fd7",
          "sha1": "bbeac18debcbf041b558163f370e3c1d80c8b7d0",
          "md5": "e1f0de6a45a2fb26e5dde52f0dd2f56a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-bom",
          "version": {
            "requires": "2.2.21"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          },
          "excludes": [
            {
              "group": "junit",
              "module": "junit"
            },
            {
              "group": "org.junit.vintage",
              "module": "junit-vintage-engine"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "variant-artifacts-0.7.0.jar",
          "url": "variant-artifacts-0.7.0.jar",
          "size": 29063,
          "sha512": "4b9f62cfccf074534a2a959b633a7c5b7bd785340c4c570a29f35e76de9fe53e3de4919f1818a1d2a558568e1dc3363ee250b9c6aeffcb67d1a6b873b9148f7b",
          "sha256": "da74ae4a28b302eb27fc8f38990aef916b2b24c0127df926295810c710f87fd7",
          "sha1": "bbeac18debcbf041b558163f370e3c1d80c8b7d0",
          "md5": "e1f0de6a45a2fb26e5dde52f0dd2f56a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "variant-artifacts-0.7.0-sources.jar",
          "url": "variant-artifacts-0.7.0-sources.jar",
          "size": 9290,
          "sha512": "98af266517e13daa0ca694a8f15acce5b026eb27f793cb466fb8ad0e8b58349ce4827a28825b8290afb8d7efe768943853a45cbf77e427b74f73fdaff019eb63",
          "sha256": "0b83242c6794123826febf2f965d6e7167234a7578345e2f389fb831dd984cec",
          "sha1": "ca8a29f8da372416c4c88097b940c6ae674f8845",
          "md5": "67350deb2d8a8e21e7554902628cc7c0"
        }
      ]
    }
  ]
}
