{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "builder",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-9.3.2.jar",
          "url": "builder-9.3.2.jar",
          "size": 17829899,
          "sha512": "cd8edb78c23beb6f54f9f58bb2fbe46655e076a701ee71c3305779a33e20b2e5bde1ae41f09084771c347157aca64d8a77d0fd6d59d0068849d5e9004f2e28d7",
          "sha256": "20dd166889b8108243b019779bdfecf7a08208ae4165f88a2a3422f34ae9e282",
          "sha1": "00f9fdaab774037c649303d97015bfb4ffe3d6f1",
          "md5": "810afbba1c60db60cc77ecccff006028"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-model",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdklib",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "sdk-common",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.ddms",
          "module": "ddmlib",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android",
          "module": "signflinger",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "protos",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.analytics-library",
          "module": "tracker",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android.tools.layoutlib",
          "module": "layoutlib-api",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.79"
          }
        },
        {
          "group": "javax.inject",
          "module": "javax.inject",
          "version": {
            "requires": "1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "manifest-merger",
          "version": {
            "requires": "32.3.2"
          }
        },
        {
          "group": "com.android",
          "module": "zipflinger",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apksig",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "apkzlib",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javawriter",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "builder-9.3.2.jar",
          "url": "builder-9.3.2.jar",
          "size": 17829899,
          "sha512": "cd8edb78c23beb6f54f9f58bb2fbe46655e076a701ee71c3305779a33e20b2e5bde1ae41f09084771c347157aca64d8a77d0fd6d59d0068849d5e9004f2e28d7",
          "sha256": "20dd166889b8108243b019779bdfecf7a08208ae4165f88a2a3422f34ae9e282",
          "sha1": "00f9fdaab774037c649303d97015bfb4ffe3d6f1",
          "md5": "810afbba1c60db60cc77ecccff006028"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-9.3.2-javadoc.jar",
          "url": "builder-9.3.2-javadoc.jar",
          "size": 337865,
          "sha512": "fda72d70323012c03fe3038f34e67bd09999e4ace19eaf4c88fbc54ef0e70d32f8633a1aaa9766ddffc8503a2ed5e5bffd34ef5566411e5da58d8b93b8089abc",
          "sha256": "ed59ff29f12276bc9bebd36bbdd7a67a86e664f72a42042c7d030e15ba468fdb",
          "sha1": "3e97dae9f020a1faca4d6e3fd018e3f41f175380",
          "md5": "d027b897f2fd5ba55baf99589e4a10b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "builder-9.3.2-sources.jar",
          "url": "builder-9.3.2-sources.jar",
          "size": 296433,
          "sha512": "a8ed53359bbbee302fd8856e09d89e71cdc7950a88501582a6c4867b8f191b57f2e17cc503db7f1bc14ba43d398d12f61649f24724aada5895151b2851ee9534",
          "sha256": "a2423c86f77ed1715f9becf9b90e63c9806eaee69908bb41d048b9156de3792c",
          "sha1": "ef2af82a27c4fe3f5bcc8de509c330276e0b46cb",
          "md5": "94a4a4a6f6fca551e26c15c449d8d29f"
        }
      ]
    }
  ]
}
