{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autonomousapps",
    "module": "kotlin-editor-relocated",
    "version": "0.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-editor-relocated-0.25.0.jar",
          "url": "kotlin-editor-relocated-0.25.0.jar",
          "size": 2761806,
          "sha512": "55956422d2fd1fca999a823230c96a26423a413ef0ce4a0edc6d0b1430e3b7fc03d0849af9b44c8fe96ba512d9d5ea60e80e21ccaa620351d7814c18845f2d6d",
          "sha256": "95a6a040b8d869cbf1c91cbbdc012d7049347e27566f4eb4a2f3409550027be8",
          "sha1": "3a325608d3c8b58480cb5ae93695b25b443408c1",
          "md5": "90fdbc1f260986dd1fb1350d029586fe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-editor-relocated-0.25.0-sources.jar",
          "url": "kotlin-editor-relocated-0.25.0-sources.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
