{
  "formatVersion": "1.1",
  "component": {
    "group": "com.android.tools.build",
    "module": "gradle-api",
    "version": "9.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.3.2.jar",
          "url": "gradle-api-9.3.2.jar",
          "size": 413599,
          "sha512": "c041012e6dda73e66c83c0e889105c6b33843ca7e205b96cc0bd2255064d72779698c5022da37acec40c1898ed5ea46f16c5d057d964f1b7c80c79c0055758df",
          "sha256": "0906266b237039241e905c96880febb5784bb91e57ef0ef91de08eab8a329b21",
          "sha1": "235bc40d88166150741dbd287d5456167533d4c0",
          "md5": "76d88a5053b05776e27cff4787a0fa23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "builder-test-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-jre"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-common-api",
          "version": {
            "requires": "9.3.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "9.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "gradle-api-9.3.2.jar",
          "url": "gradle-api-9.3.2.jar",
          "size": 413599,
          "sha512": "c041012e6dda73e66c83c0e889105c6b33843ca7e205b96cc0bd2255064d72779698c5022da37acec40c1898ed5ea46f16c5d057d964f1b7c80c79c0055758df",
          "sha256": "0906266b237039241e905c96880febb5784bb91e57ef0ef91de08eab8a329b21",
          "sha1": "235bc40d88166150741dbd287d5456167533d4c0",
          "md5": "76d88a5053b05776e27cff4787a0fa23"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.3.2-javadoc.jar",
          "url": "gradle-api-9.3.2-javadoc.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradle-api-9.3.2-sources.jar",
          "url": "gradle-api-9.3.2-sources.jar",
          "size": 385642,
          "sha512": "a997f0b5988bd2e9d1da89eab0612924fa306ed20b8a9e0ac3cbeef778f6bf7b58015816de3b5a3aaf2d594b76f0c06dfd7f19f6f48b8796d59f8a502864018b",
          "sha256": "f6bb5c976426836f1bd25b04a1d7bfde32d8dfc4d681ff38b86dfb6160e2790b",
          "sha1": "4d3be9e007e399776bacd3dcffc74d57d04e90f1",
          "md5": "722cf158f1791654e0033629ed62f1c4"
        }
      ]
    }
  ]
}
